//! Derived views — the replayed state written back out in the corpus's own file shapes.
//!
//! The log is the source of truth (record D1); a view is a projection of it, regenerated and
//! never hand-edited. Wave 1 emits views only under an explicit `--out`, so no shipped file is
//! written; from wave 6 they relocate repo-side outside `plugins/` (record D9).
//!
//! The views MUST stay human-readable text (record D6): they are the author≠grader read path and
//! the GI-006 reconstruction surface. That is why this module carries a small YAML writer instead
//! of handing a value to a generic serializer — the corpus's shape is block scalars for long
//! text, inline sequences for label and enforces lists, and inline mappings for `when:` terms, and
//! a serializer that quoted every string onto one line would satisfy the parser while destroying
//! the surface the constraint is about.
//!
//! **What a view cannot preserve**, stated rather than glossed:
//!
//! * **Comments.** They do not survive a typed model. The command runtime-kernel header is
//!   regenerated exactly (it is a template over the command's name — verified against all six);
//!   every other comment, including the per-skill headers and the inline `vars` notes, is lost.
//!   The two `enforces: []` reasons are the exception: genesis lifts them into `note:` fields, so
//!   they survive as data.
//! * **Rule field order.** It normalises on emit (P1's A11).
//! * **Scalar style and blank lines.** A string is written in the style this module picks, not
//!   the one the file used.
//!
//! So the view test asserts **semantic** equality through the canonical hash, never bytes.

use crate::model::{DocKind, DocRef, Document};
use crate::replay::State;
use serde_norway::{Mapping, Value};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// The column a folded scalar wraps at, counting its indentation.
const WIDTH: usize = 98;

/// The longest item, and the longest whole rendering, an inline sequence may carry before it is
/// written as a block. Keeps `labels:` and `enforces:` on one line the way the corpus writes
/// them, without folding a list of prose strings into an unreadable run.
const INLINE_ITEM_MAX: usize = 60;
const INLINE_TOTAL_MAX: usize = 120;

/// The runtime-kernel header every command schema carries. Verified against all six shipped
/// command schemas: they are this text with the command's own name, and nothing else differs.
const COMMAND_HEADER: &str = "\
# Command content schema for /mochiko:{name}. The command .md instructs a raw, full Read of
# this file at command fire; the model interprets it live — the .md Rules block carries the
# reading grammar. Two semantics live only here:
#   class   floor = non-waivable · must = binding obligation · advisory = guidance, not binding.
#   conditions:  each dimension declares its resolution point (entry-derived · surface-presence ·
#           moment-resolved(<moment>) · user-ruled · standing-trigger); a moment-resolved
#           dimension is unresolved until its named moment — rules gated on it are inapplicable
#           until then.
";

/// What every other kind's view says instead of the comment block it cannot reconstruct.
const DERIVED_HEADER: &str =
    "# Derived view — regenerated by `mochiko-cli views emit` from the migration log. Never \
     hand-edited.\n";

// ---------------------------------------------------------------------------
// paths, headers, documents
// ---------------------------------------------------------------------------

/// Where a document's view sits, relative to the repository root — the path its shipped file
/// occupies today, so a regenerated tree diffs directly against the real one.
pub fn view_path(doc: &DocRef) -> PathBuf {
    match doc.kind {
        DocKind::Skill => PathBuf::from(format!("plugins/mochiko/skills/{}/schema.yaml", doc.name)),
        _ => PathBuf::from(format!("plugins/mochiko/schemas/{}.yaml", doc.name)),
    }
}

/// The comment header a view opens with.
pub fn header(doc: &DocRef) -> String {
    match doc.kind {
        DocKind::Command => COMMAND_HEADER.replace("{name}", &doc.name),
        _ => DERIVED_HEADER.to_string(),
    }
}

/// One document's whole view: its header, then its content.
pub fn render(doc: &DocRef, document: &Document) -> String {
    format!("{}{}", header(doc), to_yaml(&document.to_value()))
}

/// Every document's view, addressed by its repository-relative path, in state order.
pub fn emit(state: &State) -> Vec<(PathBuf, String)> {
    state
        .docs
        .iter()
        .map(|(doc, document)| (view_path(doc), render(doc, document)))
        .collect()
}

/// Write every view under `out`, creating the directories it needs. Returns what it wrote.
///
/// `out` is required by the caller (`views emit --out <dir>` has no default), so this can never
/// overwrite a shipped file by omission.
pub fn emit_to(state: &State, out: &Path) -> std::io::Result<Vec<PathBuf>> {
    let mut written = Vec::new();
    for (relative, text) in emit(state) {
        let path = out.join(relative);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&path, text)?;
        written.push(path);
    }
    Ok(written)
}

// ---------------------------------------------------------------------------
// the writer
// ---------------------------------------------------------------------------

/// Render a YAML value in the corpus's shape.
pub fn to_yaml(value: &Value) -> String {
    let mut out = String::new();
    match value {
        Value::Mapping(map) => write_mapping(map, 0, &mut out),
        Value::Sequence(items) => write_sequence(items, 0, &mut out),
        scalar => write_scalar("", 0, scalar, &mut out),
    }
    out
}

fn pad(indent: usize) -> String {
    " ".repeat(indent)
}

fn write_mapping(map: &Mapping, indent: usize, out: &mut String) {
    for (key, value) in map {
        let key = key_text(key);
        write_entry(&key, value, indent, out);
    }
}

/// A mapping key. Keys in this corpus are plain slugs; anything else is quoted so the file still
/// parses back to the same key.
fn key_text(key: &Value) -> String {
    match key {
        Value::String(s) if !needs_quote(s, false) && !s.is_empty() => s.clone(),
        Value::String(s) => quoted(s),
        other => scalar_token(other),
    }
}

fn write_entry(key: &str, value: &Value, indent: usize, out: &mut String) {
    match value {
        Value::Mapping(map) if map.is_empty() => {
            let _ = writeln!(out, "{}{key}: {{}}", pad(indent));
        }
        // `when:` is a conjunction of a few short terms, and the corpus writes it inline. Keyed
        // on the field rather than on shape, so a `vars:` block of short scalars is never
        // collapsed into a flow mapping it was not written as.
        Value::Mapping(map) if key == "when" && flow_mapping(map).is_some() => {
            let _ = writeln!(
                out,
                "{}{key}: {}",
                pad(indent),
                flow_mapping(map).expect("checked")
            );
        }
        Value::Mapping(map) => {
            let _ = writeln!(out, "{}{key}:", pad(indent));
            write_mapping(map, indent + 2, out);
        }
        Value::Sequence(items) if items.is_empty() => {
            let _ = writeln!(out, "{}{key}: []", pad(indent));
        }
        Value::Sequence(items) if flow_sequence(items).is_some() => {
            let _ = writeln!(
                out,
                "{}{key}: {}",
                pad(indent),
                flow_sequence(items).expect("checked")
            );
        }
        Value::Sequence(items) => {
            let _ = writeln!(out, "{}{key}:", pad(indent));
            write_sequence(items, indent + 2, out);
        }
        scalar => write_scalar(&format!("{key}: "), indent, scalar, out),
    }
}

fn write_sequence(items: &[Value], indent: usize, out: &mut String) {
    for item in items {
        match item {
            Value::Mapping(map) if !map.is_empty() => {
                // Render the item at the entry indent, then turn its first line's indentation
                // into the dash. Nested blocks keep their own indentation untouched.
                let mut body = String::new();
                write_mapping(map, indent + 2, &mut body);
                let _ = write!(out, "{}- {}", pad(indent), &body[indent + 2..]);
            }
            Value::Mapping(_) => {
                let _ = writeln!(out, "{}- {{}}", pad(indent));
            }
            Value::Sequence(nested) if nested.is_empty() => {
                let _ = writeln!(out, "{}- []", pad(indent));
            }
            Value::Sequence(nested) if flow_sequence(nested).is_some() => {
                let _ = writeln!(
                    out,
                    "{}- {}",
                    pad(indent),
                    flow_sequence(nested).expect("checked")
                );
            }
            Value::Sequence(nested) => {
                let _ = writeln!(out, "{}-", pad(indent));
                write_sequence(nested, indent + 2, out);
            }
            scalar => write_scalar("- ", indent, scalar, out),
        }
    }
}

/// Write one scalar behind `prefix` (`"key: "` or `"- "`), choosing the style the corpus uses:
/// a literal block for anything carrying newlines, a folded block for a long single line, and a
/// plain or quoted token otherwise.
fn write_scalar(prefix: &str, indent: usize, value: &Value, out: &mut String) {
    let Value::String(text) = value else {
        let _ = writeln!(out, "{}{prefix}{}", pad(indent), scalar_token(value));
        return;
    };

    if text.contains('\n') {
        if let Some((header, lines)) = literal_block(text) {
            let _ = writeln!(out, "{}{prefix}{header}", pad(indent));
            for line in lines {
                if line.is_empty() {
                    out.push('\n');
                } else {
                    let _ = writeln!(out, "{}{line}", pad(indent + 2));
                }
            }
            return;
        }
        // A first line opening with whitespace would need an explicit indentation indicator to
        // read back the same; a quoted scalar is unambiguous, so take that rather than risk it.
        let _ = writeln!(out, "{}{prefix}{}", pad(indent), double_quoted(text));
        return;
    }

    let inline = if needs_quote(text, false) {
        quoted(text)
    } else {
        text.clone()
    };
    let fits = indent + prefix.len() + inline.len() <= WIDTH;
    if fits || !foldable(text) {
        let _ = writeln!(out, "{}{prefix}{inline}", pad(indent));
        return;
    }

    let _ = writeln!(out, "{}{prefix}>-", pad(indent));
    for line in fold(text, WIDTH.saturating_sub(indent + 2)) {
        let _ = writeln!(out, "{}{line}", pad(indent + 2));
    }
}

/// The literal-block header and body lines, or `None` when the text cannot be written as one.
fn literal_block(text: &str) -> Option<(&'static str, Vec<&str>)> {
    let trailing = text.len() - text.trim_end_matches('\n').len();
    let header = match trailing {
        0 => "|-",
        1 => "|",
        _ => "|+",
    };
    let body = if trailing == 0 {
        text
    } else {
        &text[..text.len() - (trailing - usize::from(trailing == 1))]
    };
    let body = body.strip_suffix('\n').unwrap_or(body);
    let mut lines: Vec<&str> = body.split('\n').collect();
    // A body line ending in whitespace, or a first line opening with it, does not read back
    // unchanged without an indentation indicator.
    if lines.first().is_some_and(|l| l.starts_with([' ', '\t'])) {
        return None;
    }
    if lines.iter().any(|l| l.ends_with([' ', '\t'])) {
        return None;
    }
    // `|+` keeps the newlines that are actually written after the body, so the ones past the
    // first have to be emitted as blank lines. Writing the header alone keeps nothing, which is
    // how a two-newline string used to read back with one.
    lines.extend(std::iter::repeat_n("", trailing.saturating_sub(1)));
    Some((header, lines))
}

/// Whether a single-line string survives folding. Folding joins lines with a space, so any run
/// of two spaces, or an edge space, would come back different.
///
/// Deliberately not gated on `needs_quote`. Inside a folded block a colon, a hash, a leading dash
/// and a quote are all literal text, and every emitted line is padded to the same column, so none
/// of the inline hazards apply. Requiring an unquotable string here only made the views
/// longer-lined than the corpus they mirror, which is the readability D6 asks for.
fn foldable(text: &str) -> bool {
    !text.contains("  ")
        && !text.starts_with([' ', '\t'])
        && !text.ends_with([' ', '\t'])
        && !text.chars().any(char::is_control)
}

/// Wrap on single spaces at `width`. Every line begins with a word character, so no line reads
/// as more-indented content, which is the one way a folded block changes meaning.
fn fold(text: &str, width: usize) -> Vec<String> {
    let mut lines = Vec::new();
    let mut line = String::new();
    for word in text.split(' ') {
        if line.is_empty() {
            line.push_str(word);
        } else if line.len() + 1 + word.len() <= width {
            line.push(' ');
            line.push_str(word);
        } else {
            lines.push(std::mem::take(&mut line));
            line.push_str(word);
        }
    }
    if !line.is_empty() {
        lines.push(line);
    }
    lines
}

/// A sequence rendered inline, or `None` when it must be written as a block.
fn flow_sequence(items: &[Value]) -> Option<String> {
    let mut parts = Vec::with_capacity(items.len());
    for item in items {
        let token = match item {
            Value::String(s) if !needs_quote(s, true) && s.len() <= INLINE_ITEM_MAX => s.clone(),
            Value::Bool(_) | Value::Number(_) | Value::Null => scalar_token(item),
            _ => return None,
        };
        parts.push(token);
    }
    let rendered = format!("[{}]", parts.join(", "));
    (rendered.len() <= INLINE_TOTAL_MAX).then_some(rendered)
}

/// A mapping rendered inline, or `None` when it must be written as a block. Values may be
/// scalars or short scalar sequences — the two shapes a `when:` term is written in.
fn flow_mapping(map: &Mapping) -> Option<String> {
    let mut parts = Vec::with_capacity(map.len());
    for (key, value) in map {
        let Value::String(key) = key else {
            return None;
        };
        if needs_quote(key, true) {
            return None;
        }
        let token = match value {
            Value::String(s) if s.len() <= INLINE_ITEM_MAX => {
                if needs_quote(s, true) {
                    quoted(s)
                } else {
                    s.clone()
                }
            }
            Value::Bool(_) | Value::Number(_) | Value::Null => scalar_token(value),
            Value::Sequence(items) => flow_sequence(items)?,
            _ => return None,
        };
        parts.push(format!("{key}: {token}"));
    }
    let rendered = format!("{{{}}}", parts.join(", "));
    (rendered.len() <= INLINE_TOTAL_MAX).then_some(rendered)
}

fn scalar_token(value: &Value) -> String {
    match value {
        Value::Null => "null".to_string(),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => n.to_string(),
        Value::String(s) => {
            if needs_quote(s, false) {
                quoted(s)
            } else {
                s.clone()
            }
        }
        other => serde_norway::to_string(other)
            .unwrap_or_default()
            .trim_end()
            .to_string(),
    }
}

/// Whether a string must be quoted to read back as itself. `flow` adds the indicators that only
/// bite inside `[...]` and `{...}`, so a block-context string keeps the commas and brackets the
/// corpus writes plainly.
fn needs_quote(text: &str, flow: bool) -> bool {
    if text.is_empty() {
        return true;
    }
    if text.starts_with([' ', '\t']) || text.ends_with([' ', '\t']) {
        return true;
    }
    if text.contains('\n') || text.contains('\t') {
        return true;
    }
    let first = text.chars().next().expect("non-empty");
    if "-?:,[]{}#&*!|>'\"%@`".contains(first) {
        return true;
    }
    if text.contains(": ") || text.contains(" #") || text.ends_with(':') {
        return true;
    }
    if flow && text.contains([',', '[', ']', '{', '}']) {
        return true;
    }
    // Tokens a reader would resolve to something other than a string. YAML 1.1 readers take the
    // whole `y/yes/on` family, and the shipped corpus quotes them, so this writer does too.
    let lower = text.to_ascii_lowercase();
    if matches!(
        lower.as_str(),
        "y" | "n"
            | "yes"
            | "no"
            | "true"
            | "false"
            | "on"
            | "off"
            | "null"
            | "nil"
            | "~"
            | ".nan"
            | ".inf"
            | "-.inf"
    ) {
        return true;
    }
    if text.parse::<f64>().is_ok() || text.parse::<i64>().is_ok() {
        return true;
    }
    false
}

/// Single-quoted style: the only escape is a doubled quote, so nothing else can change meaning.
fn quoted(text: &str) -> String {
    format!("'{}'", text.replace('\'', "''"))
}

/// Double-quoted style, for the rare scalar a literal block cannot carry.
fn double_quoted(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for ch in text.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            other => out.push(other),
        }
    }
    out.push('"');
    out
}
