/// The 114 probe names of `scripts/test-check-skill-schema.py`, verbatim.
const PYTHON_PROBES: [&str; 114] = [
    "baseline pair is clean",
    "the schema missing its kind: discriminator",
    "the schema missing its skill: name",
    "the skill: name disagreeing with its directory",
    "the registry missing its kind: discriminator",
    "the registry carrying no labels mapping",
    "the library missing its kind: discriminator",
    "the schema does not parse as YAML",
    "the SKILL.md file is missing entirely",
    "the schema carrying no sections",
    "a flat top-level rules: key",
    "canonical section absent",
    "a section outside the canonical six (the command six-set is not this grammar)",
    "a section ID leading with a foreign stem",
    "an empty section carrying no note",
    "an empty section written as `rules:` rather than `rules: []`",
    "a duplicate rule ID",
    "a rule id outside the dotted-slug format",
    "a rule id leading with a foreign stem",
    "a rule missing its id",
    "a class outside floor|must|advisory",
    "a rule carrying no labels",
    "a rule carrying no text",
    "a label outside the registry",
    "a kind outside the eight-kind set",
    "kind: fail names its census retirement, not a generic vocabulary miss",
    "enforces: anywhere in a skill schema",
    "a moments: block in a skill schema",
    "every legal kind is admitted",
    "an absent kind reads constraint, never a finding",
    "when: names an undeclared dimension",
    "when: names an undeclared value",
    "when: written as a list, not a conjunction mapping",
    "a moment-resolved resolution point is command grammar",
    "a resolution point outside the skill set",
    "a declared dimension no rule uses is a warning",
    "a declared value named by no rule's when: is a warning",
    "the coverage report makes no claim over floors",
    "extends: names no block in the library",
    "extends: target outside the review-common.<slug> format",
    "an extends: stub declaring no local class",
    "the family library absent while a stub binds it",
    "a common block carrying `kind:`",
    "a common block carrying `when:`",
    "a common block carrying `enforces:`",
    "a common block id outside the review-common.<slug> format",
    "a stub whose local text repeats the block's",
    "an orphan ${var} inherited from a common block is attributed to the stub",
    "[sweep] a common block bound by no stub in any swept skill",
    "a single-skill run makes no orphan claim",
    "the in-directory and cross-directory pointers of the baseline resolve",
    "a pointer to a file that does not exist",
    "a cross-directory climb to a file that does not exist",
    "an absolute pointer path",
    "a skill-name pointer is a name, not a path — skipped",
    "a fabricated citation dangles",
    "a citation of a tombstoned rule is a superseded reference",
    "a section-ID citation resolves",
    "a foreign-stem citation is a warning, not a dangle",
    "rule text naming a section that never existed",
    "rule text naming a tombstoned section",
    "an orphan ${var} placeholder",
    "a declared var no rule text uses",
    "a deictic reference is a warning",
    "an ID both live and tombstoned",
    "a tombstone entry missing its disposition",
    "the pin names the wrong number",
    "the pin absent entirely",
    "the pin plural where the count is 1",
    "a re-pinned count survives cleanly",
    "a second, disagreeing pin elsewhere in the body is caught",
    "the Rules heading absent",
    "the Rules block omits a live section",
    "the Rules block names a section the schema lacks",
    "a tombstoned token inside the Rules block gets the tombstone message",
    "a dangling token outside the Rules block",
    "a tombstoned token in the SKILL.md",
    "a foreign-stem token in the SKILL.md is a warning",
    "the sidecar absent is a warning, not a finding",
    "a dangling skill-prefixed entry",
    "an entry naming a tombstoned rule",
    "an anchor that is malformed",
    "an anchor resolving to no DECISIONS.md row",
    "a foreign-prefix entry is skipped silently",
    "the pre-rename command-provenance kind is accepted",
    "a kind outside both provenance discriminators",
    "the authoring baseline pair is clean",
    "[authoring] the canonical artifact section absent",
    "[authoring] a verdict section is the review set, not this family's",
    "[review] an artifact section is the authoring set, not this family's",
    "[authoring] a stub extending the review family's library is cross-family",
    "a review stub extending the authoring family's library is cross-family",
    "[authoring] extends: names no block in the authoring library",
    "[authoring] the authoring library absent while a stub binds",
    "[authoring] a block id outside the authoring-common.<slug> format",
    "[authoring] the library missing its kind: discriminator",
    "[authoring] an orphan ${template} is attributed to the binding stub",
    "[authoring] an extends: stub declaring no local class",
    "[authoring] a stub inheriting a label-less block warns, never fails",
    "a stub with a LOCAL empty labels: is still a finding",
    "[sweep] all-bound authoring blocks make no orphan claim and no label claim",
    "[sweep] no authoring schemas swept makes no authoring orphan claim",
    "[sweep] a label unused by every swept schema is named once, at sweep end",
    "[sweep] labels all carried across the swept schemas make no claim",
    "a single-skill run makes no zero-member label claim",
    "the patterns baseline pair is clean",
    "[patterns] the canonical trigger section absent",
    "[patterns] a verdict section is the review set, not this family's",
    "[patterns] an artifact section is the authoring set, not this family's",
    "[review] a discipline section is the patterns set, not this family's",
    "[patterns] any extends: is the no-common-file finding",
    "[patterns] a stub naming a real other-family block still gets the no-library finding",
    "[sweep] a schema-less patterns member is never swept, never demanded of",
    "[sweep] the sweep makes no patterns orphan claim",
];
